import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGame,draft,declare,legalActions,applyAction,chooseAI,validateGame,authority,resolveEvent,revealFragment,type Game} from '../src/engine';
import {card,HOUSES,ENCOUNTERS} from '../src/content';
function setup(seed=42,house=HOUSES[0].id){const g=createGame({seed,house});while(g.phase==='draft'){const hand=[...g.players[0].hand].sort((a,b)=>(card(a).house===house?10:0)+(card(a).role==='Founder'?4:0)-(card(b).house===house?10:0)-(card(b).role==='Founder'?4:0));draft(g,hand.slice(0,3-g.draftStep));}declare(g,g.players[0].hand.filter(id=>card(id).house===house).slice(0,3));return g;}
test('draft conserves all unique cards through 3–2–1 and declaration',()=>{for(let seed=1;seed<50;seed++){const g=setup(seed);assert.ok(validateGame(g));assert.equal(g.phase,'play');assert.equal(g.players[0].hand.length,5);assert.equal(g.market.length,4);}});
test('invalid moves are atomic and do not change state',()=>{const g=setup();const before=JSON.stringify(g);assert.throws(()=>applyAction(g,{type:'build',cards:['made-up'],label:'',detail:''}));assert.equal(JSON.stringify(g),before);});
test('replay is deterministic',()=>{const run=()=>{const g=setup(1603);for(let i=0;i<70&&g.phase!=='over';i++)applyAction(g,chooseAI(g));return JSON.stringify(g);};assert.equal(run(),run());});
test('nine fragments ends the game for every dynasty',()=>{const g=setup();g.paintings=[8,8,8];revealFragment(g);assert.equal(g.winner,-1);assert.equal(g.phase,'over');});
test('schism removes marriage authority without removing cards',()=>{const g=setup();const p=g.players[0];const q=p.court.find(id=>card(id).role==='Queen');if(!q)return;const foreign=g.deck.find(id=>card(id).house!==p.house)!;g.deck=g.deck.filter(id=>id!==foreign);p.court.push(foreign);p.marriages=[{queen:q,house:card(foreign).house}];const before=authority(g,p);resolveEvent(g,1);assert.equal(p.marriages.length,0);assert.equal(authority(g,p),before-1);assert.ok(p.court.includes(foreign));assert.ok(validateGame(g));});
test('protection absorbs a historical loss',()=>{const g=setup();const p=g.players[0];const id=p.hand[0];p.hand.shift();p.court.push(id);p.ward=1;const n=p.court.length;resolveEvent(g,0);assert.equal(p.court.length,n);assert.equal(p.ward,0);});
test('AI cannot target a protected Founder while another Royal remains',()=>{const g=setup();for(const a of legalActions(g)){if(a.targetCard&&card(a.targetCard).role==='Founder')assert.equal(g.players[a.target!].court.length,1);}});
test('hundreds of complete games preserve card conservation and terminate',()=>{for(let n=0;n<180;n++){const h=HOUSES[n%6].id;const g=setup(n+100,h);g.modifier=ENCOUNTERS[n%9].mod;g.goal=ENCOUNTERS[n%9].goal;for(let i=0;i<180&&g.phase!=='over';i++){applyAction(g,chooseAI(g));assert.ok(validateGame(g),`invalid state seed ${n+100}, turn ${i}`);}assert.equal(g.phase,'over',`nonterminal seed ${n+100}`);}});
test('saving and resuming preserves the next legal move and outcome',()=>{const g=setup(1485);for(let i=0;i<7;i++)applyAction(g,chooseAI(g));const copy:Game=JSON.parse(JSON.stringify(g));assert.ok(validateGame(copy));assert.deepEqual(chooseAI(g),chooseAI(copy));});
test('even hostile drafting can recover a valid declaration without creating cards',()=>{for(let n=0;n<500;n++){const h=HOUSES[n%6].id;const g=createGame({seed:n,house:h});while(g.phase==='draft'){const order=[...g.players[0].hand].sort((a,b)=>(card(b).house===h?10:0)-(card(a).house===h?10:0));draft(g,order.slice(0,3-g.draftStep));}const native=g.players[0].hand.filter(id=>card(id).house===h);assert.ok(native.length>=3,`seed ${n}`);declare(g,native.slice(0,3));assert.ok(validateGame(g));}});
test('corrupt saves fail closed instead of throwing',()=>{assert.equal(validateGame({version:1} as Game),false);const g=setup();g.winner=100 as 0;assert.equal(validateGame(g),false);});
test('a claim is not an immediate win and spends one protection',()=>{const g=setup();const p=g.players[0];g.goal=authority(g,p)+1;p.ward=2;const a=legalActions(g).find(a=>a.type==='build');assert.ok(a);applyAction(g,a);assert.equal(g.phase,'play');assert.equal(p.claim,true);assert.equal(p.ward,1);});
test('all strategic action families can execute and preserve unique cards',()=>{const seen=new Set<string>();for(let n=0;n<150;n++){const g=setup(900+n,HOUSES[n%6].id);g.modifier='intrigue';for(let i=0;i<55&&g.phase!=='over';i++){const actions=legalActions(g);const a=actions.find(a=>!seen.has(a.type))??chooseAI(g);seen.add(a.type);applyAction(g,a);assert.ok(validateGame(g));}}assert.deepEqual([...seen].sort(),['barter','betray','build','marry','scheme','seize']);});
