import { chromium, expect } from "@playwright/test";
const b = await chromium.launch({ channel: "chrome", headless: true });
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
const errors: string[] = [];
p.on("pageerror", (e) => errors.push(e.message));
await p.goto("http://localhost:5173/?legacy=1");
await p.locator('[data-start="lesson"]').click();
await p.waitForTimeout(600);
await p.locator(".hand-card").click();
await p.screenshot({ path: "artifacts/physical/final-selected.png" });
await p.locator('[data-move*=\'"type":"deploy"\']').click();
await p.waitForTimeout(220);
await p.screenshot({ path: "artifacts/physical/final-deployment.png" });
await expect(p.locator("[data-next-lesson]")).toBeVisible();
await expect(p.locator('.physical-card[data-owner="0"]')).toHaveCount(2);
await p.locator("[data-next-lesson]").click();
await p.locator('.physical-card[data-owner="0"] [data-royal]').first().click();
await p.locator('.physical-card[data-owner="1"] .targetable').first().click();
await p.locator('[data-move*=\'"type":"attack"\']').click();
await p.waitForTimeout(300);
await p.screenshot({ path: "artifacts/physical/final-combat.png" });
await expect(p.locator("[data-next-lesson]")).toBeVisible();
expect(errors).toEqual([]);
console.log("Motion-enabled deployment and combat completed without errors");
await b.close();
