export type HouseId = 'alba'|'plantagenet'|'tudor'|'valois'|'habsburg'|'bourbon';
export type Role = 'Founder'|'Queen'|'Warlord'|'Lawgiver'|'Intriguer'|'Royal';
export interface Card { id:string; house:HouseId; name:string; role:Role; epithet:string; art:string; }
export interface House { id:HouseId; name:string; region:string; motto:string; color:string; emblem:string; trait:string; description:string; leader:string; }
export const HOUSES:House[]=[
 {id:'alba',name:'Alba',region:'SCOTLAND',motto:'From stone, a kingdom.',color:'#6fa997',emblem:'✥',trait:'Stone & steel',description:'Your Founder grants 2 protection instead of 1 when declared or built. Survive the storm, then rise.',leader:'Kenneth MacAlpin'},
 {id:'plantagenet',name:'Plantagenet',region:'ENGLAND & AQUITAINE',motto:'The lion does not kneel.',color:'#d6a357',emblem:'♜',trait:'Lionheart',description:'A Warlord in your hand can seize with any other card. Hidden force becomes an unexpected claim.',leader:'Eleanor of Aquitaine'},
 {id:'tudor',name:'Tudor',region:'ENGLAND',motto:'A crown worth any secret.',color:'#c27979',emblem:'❀',trait:'The hidden court',description:'Your Intriguers may betray any unprotected rival, even without a marriage. Secrets cross every border.',leader:'Elizabeth I'},
 {id:'valois',name:'Valois',region:'FRANCE',motto:'Power is an art.',color:'#929bc8',emblem:'⚜',trait:'Patron of the arts',description:'Each Lawgiver you build veils one fragment of Eudoxia’s most complete painting. Patronage buys time.',leader:'Francis I'},
 {id:'habsburg',name:'Habsburg',region:'AUSTRIA & EUROPE',motto:'Let others wage war.',color:'#c6b588',emblem:'♛',trait:'The marriage empire',description:'Each living marriage grants 1 additional authority. Alliances can win a crown—and lose it.',leader:'Maria Theresa'},
 {id:'bourbon',name:'Bourbon',region:'FRANCE',motto:'All roads lead to the sun.',color:'#79a6c4',emblem:'☀',trait:'The sun court',description:'Your declared Founder grants 1 additional authority. A brilliant court is a tempting target.',leader:'Louis XIV'}
];
export const house=(id:HouseId)=>HOUSES.find(h=>h.id===id)!;
const lists:Record<HouseId,[string,Role,string][]>={
 alba:[['Kenneth MacAlpin','Founder','The first claim'],['St Margaret','Queen','A kingdom’s conscience'],['Malcolm III','Warlord','Canmore'],['David I','Lawgiver','The reforming king'],['William the Lion','Warlord','The lion of Scotland'],['Alexander II','Royal','Keeper of the border'],['Alexander III','Royal','The golden peace'],['Robert the Bruce','Warlord','The unbroken claim'],['Marjorie Bruce','Queen','Bridge of bloodlines'],['Robert II','Intriguer','A new succession'],['Duncan I','Royal','The contested throne'],['Donald II','Royal','The northern crown'],['Constantine II','Lawgiver','Keeper of the realm'],['Matilda of Scotland','Queen','The joining of crowns']],
 plantagenet:[['Henry II','Founder','An empire inherited'],['Eleanor of Aquitaine','Queen','The lioness'],['Richard I','Warlord','The Lionheart'],['John','Intriguer','The disputed king'],['Henry III','Royal','The patient crown'],['Edward I','Warlord','The long shadow'],['Edward II','Royal','A fragile inheritance'],['Edward III','Warlord','The claim across the sea'],['Philippa of Hainault','Queen','The steadfast court'],['Richard II','Intriguer','The gilded throne'],['Edward the Black Prince','Warlord','The warrior heir'],['Joan of Kent','Queen','A marriage of consequence'],['Geoffrey of Anjou','Lawgiver','The planted broom'],['Isabella of France','Queen','The she-wolf']],
 tudor:[['Henry VII','Founder','The rose united'],['Elizabeth I','Queen','The sovereign rose'],['Henry VIII','Warlord','The king’s great matter'],['Mary I','Queen','A crown reclaimed'],['Edward VI','Lawgiver','The young reformer'],['Elizabeth of York','Queen','Two roses, one crown'],['Margaret Beaufort','Intriguer','The king’s mother'],['Edmund Tudor','Royal','An uncertain beginning'],['Jasper Tudor','Warlord','The loyal uncle'],['Margaret Tudor','Queen','The northern marriage'],['Mary Tudor of France','Queen','The French marriage'],['Arthur Tudor','Royal','The lost prince'],['Owen Tudor','Intriguer','The hidden beginning'],['Catherine of Aragon','Queen','The enduring claim']],
 valois:[['Philip VI','Founder','The branch becomes the tree'],['Francis I','Warlord','The Renaissance king'],['Catherine de’ Medici','Queen','The patient web'],['Charles V','Lawgiver','The wise king'],['Charles VII','Royal','The crown restored'],['Louis XI','Intriguer','The universal spider'],['Henry II','Warlord','The tournament crown'],['Charles IX','Royal','The fractured court'],['Henry III','Intriguer','The last Valois'],['Marguerite de Valois','Queen','Between two houses'],['Louis XII','Lawgiver','Father of the people'],['Claude of France','Queen','The Breton inheritance'],['Isabeau of Bavaria','Queen','The contested regency'],['John II','Royal','The captive king']],
 habsburg:[['Rudolf I','Founder','The eagle ascends'],['Maria Theresa','Queen','The unbroken empress'],['Maximilian I','Lawgiver','The last knight'],['Charles V','Warlord','A world of crowns'],['Philip I','Royal','The handsome heir'],['Ferdinand I','Lawgiver','The divided inheritance'],['Philip II','Intriguer','The patient sovereign'],['Anna of Austria','Queen','A marriage of empires'],['Margaret of Austria','Queen','The governing aunt'],['Ferdinand II','Warlord','The iron confession'],['Leopold I','Royal','The eastern shield'],['Charles VI','Lawgiver','The pragmatic claim'],['Joseph II','Lawgiver','The impatient reformer'],['Mary of Hungary','Queen','The governing sister']],
 bourbon:[['Henry IV','Founder','A kingdom reconciled'],['Louis XIV','Royal','The Sun King'],['Louis XIII','Warlord','The crown consolidated'],['Anne of Austria','Queen','The queen regent'],['Louis XV','Royal','The beloved'],['Louis XVI','Lawgiver','The final inheritance'],['Marie Antoinette','Queen','The gilded cage'],['Marie de’ Medici','Queen','The regent’s ambition'],['Philippe of Orléans','Intriguer','The brother’s court'],['Louis II de Condé','Warlord','The Great Condé'],['Antoine of Bourbon','Royal','The Navarre claim'],['Jeanne d’Albret','Queen','The sovereign of Navarre'],['Philip V of Spain','Royal','A crown beyond the mountains'],['Louis XVIII','Intriguer','The restoration']]
};
export const ROLE_TEXT:Record<Role,string>={Founder:'Anchor · 2 authority. Grants protection. Immune to seizure while your court has other Royals.',Queen:'Alliance · Once declared, may marry a foreign Royal from your hand and open their bloodline.',Warlord:'Force · Building grants 1 protection. Keep a matching pair concealed to seize a rival Royal.',Lawgiver:'Order · Building grants 1 protection. Valois Lawgivers also veil a Witness fragment.',Intriguer:'Secrets · Discard from hand to betray a rival linked by marriage. Tudor can target any rival.',Royal:'Bloodline · 1 authority when active. A matching pair in hand can seize exposed power.'};
export const CARDS:Card[]=HOUSES.flatMap(h=>lists[h.id].map(([name,role,epithet],i)=>({id:`${h.id}-${i}`,house:h.id,name,role,epithet,art:h.id})));
export const card=(id:string)=>CARDS.find(c=>c.id===id)!;
export const EVENTS=[
 {id:'plague',name:'The Black Death',subtitle:'No crown commands the plague.',text:'Every court with more than three Royals loses its newest non-Founder. Protection absorbs the loss.'},
 {id:'schism',name:'The Great Schism',subtitle:'An oath splits down the middle.',text:'Every marriage breaks. Foreign Royals lose authority until their bloodline is joined again.'},
 {id:'uprising',name:'The Peasants’ Rising',subtitle:'Below every throne, the earth moves.',text:'The leading court loses its newest non-Founder. Protection absorbs the loss. Tied leaders are all affected.'},
 {id:'peace',name:'The King’s Peace',subtitle:'For a moment, the swords are silent.',text:'All courts gain 1 protection. Protection absorbs one hostile action or historical loss.'},
 {id:'succession',name:'A Disputed Succession',subtitle:'Blood remembers. Law disagrees.',text:'Every court loses all protection. The next move may decide the inheritance.'},
 {id:'renaissance',name:'The Renaissance',subtitle:'The witness lifts her brush.',text:'Reveal two additional Eudoxia fragments. Her record draws closer to completion.'},
 {id:'harvest',name:'A Golden Harvest',subtitle:'Even history sometimes gives.',text:'All courts gain 1 protection and the public exchange receives new Royals.'},
 {id:'exile',name:'The Edict of Exile',subtitle:'A name is struck from the family book.',text:'Every court returns its newest foreign Royal to the discard archive. Native bloodlines endure.'}
];
export const PAINTINGS=['The Price of a Crown','The Feast of Wolves','The Last Witness'];
export const ENCOUNTERS=[
 {id:'border',name:'The Border Court',place:'STIRLING · THE NORTHERN CLAIM',text:'Three houses gather beneath a borrowed crown. Establish a claim before the court turns against you.',mod:'standard',rivals:['plantagenet','valois'] as HouseId[],goal:8},
 {id:'roses',name:'A Garden of Knives',place:'WESTMINSTER · THE ROSE COURT',text:'In this court, every promise conceals another intention. A veil of secrets is your best defense.',mod:'intrigue',rivals:['tudor','plantagenet'] as HouseId[],goal:8},
 {id:'bridges',name:'The Marriage Congress',place:'VIENNA · THE SILKEN ACCORD',text:'Queens decide what armies cannot. Each marriage carries an extra point of authority—for every house.',mod:'marriage',rivals:['habsburg','bourbon'] as HouseId[],goal:9},
 {id:'winter',name:'The Winter Throne',place:'CHINON · THE LONG WINTER',text:'No house begins with protection. The first to expose too much may be the first to fall.',mod:'winter',rivals:['valois','plantagenet'] as HouseId[],goal:8},
 {id:'gallery',name:'The Silent Gallery',place:'FONTAINEBLEAU · THE WATCHING EYES',text:'Eudoxia already holds three fragments. Build quickly, or make patronage your weapon.',mod:'witness',rivals:['valois','tudor'] as HouseId[],goal:8},
 {id:'eagle',name:'The Eagle’s Summit',place:'PRAGUE · THE IMPERIAL DIET',text:'The greatest houses convene. Secure a larger court and hold it through a full round of opposition.',mod:'standard',rivals:['habsburg','alba'] as HouseId[],goal:9},
 {id:'sun',name:'The Sun King’s Wager',place:'VERSAILLES · THE GILDED HOUR',text:'Every Founder carries an extra point of authority. A radiant beginning invites ruthless challengers.',mod:'founders',rivals:['bourbon','habsburg'] as HouseId[],goal:9},
 {id:'storm',name:'The Fractured Realm',place:'EUROPE · THE AGE OF INTERREGNA',text:'History interrupts every second round. Protection and careful succession will decide what survives.',mod:'storm',rivals:['alba','tudor'] as HouseId[],goal:8},
 {id:'last',name:'The Last Coronation',place:'THE HIGH COURT · A CROWN TO KEEP',text:'All roads end at this table. Eudoxia begins her final painting; one dynasty must outlast the rest.',mod:'finale',rivals:['bourbon','plantagenet'] as HouseId[],goal:10}
];
export const RELICS=[
 {id:'signet',name:'The Iron Signet',text:'Begin each encounter with 1 additional protection.',icon:'♜'},
 {id:'patron',name:'The Painter’s Favor',text:'Veil the first two fragments revealed each encounter.',icon:'◈'},
 {id:'charter',name:'The Royal Charter',text:'Your court requires 1 less authority to secure victory.',icon:'♛'},
 {id:'veil',name:'The Velvet Veil',text:'Your Intriguers may betray any unprotected rival.',icon:'✦'},
 {id:'oath',name:'The Golden Oath',text:'Your marriages grant 1 additional authority.',icon:'∞'},
 {id:'aegis',name:'The Saint’s Medallion',text:'Your protection can hold up to 3 charges instead of 2.',icon:'✥'}
];
